### ISSUE TITLE
Needs update to build with openssl 1.1.0

### ISSUE THREAD

**Issue by sney** [hexchat/hexchat#1759]
See debian bug 828339: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828339

relevant part of the build log: 

```
gcc -DHAVE_CONFIG_H -I. -I../..  -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DG_DISABLE_SINGLE_INCLUDES   -pthread -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -D_REENTRANT -I../.. -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -pipe -funsigned-char -fPIE -fPIC -Wall -Wextra -Wstrict-prototypes -Wno-unused-parameter -Wno-sign-compare -Wno-pointer-sign -Wno-missing-field-initializers -Wno-unused-result -Werror=init-self -Werror=declaration-after-statement -Werror=missing-include-dirs -Werror=date-time -Werror=implicit-function-declaration -Werror=pointer-arith -c -o libhexchatcommon_a-server.o `test -f 'server.c' || echo './'`server.c
server.c: In function 'ssl_cb_verify':
server.c:471:47: error: dereferencing pointer to incomplete type 'X509_STORE_CTX {aka struct x509_store_ctx_st}'
  X509_NAME_oneline (X509_get_subject_name (ctx->current_cert), subject,
                                               ^
server.c: In function 'ssl_do_connect':
server.c:641:16: error: dereferencing pointer to incomplete type 'SSL {aka struct ssl_st}'
   if (serv->ssl->session && serv->ssl->session->time + SSLTMOUT < time (NULL))
                ^
```

**Comment by TingPing** [comment]
Go ahead and test that commit, before pushing to master I just want to make sure that it still builds against 0.9.8 and that the new NULL check is correct.

**Comment by TingPing** [comment]
Note that as of a0e80ebda2bc9270beb4818a2438d7555593b6fd everything builds against 1.1.0, there were a few extra changes needed.

**Comment by kfogel** [comment]
It looks like the build is failing again, this time due to deprecations that have recently (?) been strengthened in OpenSSL.  I'm not sure whether I should open a new bug or re-open this one, so I'll start here.  Below is a transcript of my build attempt.  Note that `/usr/include/openssl/opensslv.h` gives`OPENSSL_VERSION_TEXT` as "OpenSSL 1.1.0c 10 Nov 2016".  (Actually, not sure whether the active definition is `1.1.0c-fips` or just `1.1.0c`; if the difference is important here let me know and I'll do some digging to find out.)

This is from a totally clean tree (I did `make clean` and even `make distclean` to be sure):

```
$ git remote show origin | grep "Fetch URL"
  Fetch URL: git@github.com:hexchat/hexchat.git
$ git log -1
commit 63e9c721148f8a91bc68484c3f9ee42cfbc4316f
Author: tomek <eustachy.kapusta@gmail.com>
Date:   Fri Dec 23 14:04:32 2016 +0100

    win32: Update Python to 3.6
$ ./autogen.sh --enable-debug --enable-textfe
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable debugging... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking how to run the C preprocessor... gcc -E
checking for gcc... gcc
checking whether we are using the GNU Objective C compiler... no
checking whether gcc accepts -g... no
checking dependency style of gcc... gcc3
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1635072
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for mdtool... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether NLS is requested... yes
checking for intltool >= 0.40.0... 0.51.0 found
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.24.1
checking for XML::Parser... ok
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for LC_MESSAGES... yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for ngettext in libc... yes
checking for dgettext in libc... yes
checking for bind_textdomain_codeset... yes
checking for msgfmt... (cached) /usr/bin/msgfmt
checking for dcgettext... yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... (cached) /usr/bin/msgfmt
checking for xgettext... (cached) /usr/bin/xgettext
checking for sed... /bin/sed
checking for uname... /bin/uname
checking system type... Linux
checking for pkg-config... (cached) /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for GLIB - version >= 2.34.0... yes (version 2.50.2)
checking for GTK... yes
checking for plugin interface used by lua... yes
checking for LUA... yes
checking for plugin interface used by Perl... yes
checking for perl... perl
checking for perl module ExtUtils::Embed... yes
checking for perl ccopts embed flags...  -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib/x86_64-linux-gnu/perl/5.24/CORE 
checking for perl ldopts embed flags... -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.24/CORE -lperl -ldl -lm -lpthread -lc -lcrypt
checking if perl plugin will be backward compatible... yes
checking for plugin interface used by Python... yes
checking for python2... /usr/bin/python2
checking for a version of Python >= '2.1.0'... yes
checking for a version of Python >= '2.7'... yes
checking for the distutils Python package... yes
checking for Python include path... -I/usr/include/python2.7
checking for Python library path... -L/usr/lib -lpython2.7
checking for Python site-packages path... /usr/lib/python2.7/dist-packages
checking python extra libraries... -lpthread -ldl  -lutil -lm
checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
checking consistency of all components of python development environment... yes
checking Python version... 2.7
checking for select... yes
checking for select in -lsocket... no
checking for getaddrinfo... yes
checking whether IPv6 is supported... yes
checking for OPENSSL... yes
checking for SSL_CTX_get_ssl_method... no
checking for X509_get_signature_nid... no
checking for DH_set0_pqg... no
checking for DH_get0_key... no
checking for DH_set0_key... no
checking for LIBPROXY... yes
checking for plugin interface used by Checksum... yes
checking for plugin interface used by FiSHLiM... yes
checking for OpenSSL used by FiSHLiM... yes
checking for plugin interface used by SysInfo... yes
checking for LIBPCI... no
checking for DBUS... yes
checking for dbus-binding-tool... /usr/bin/dbus-binding-tool
checking for LIBNOTIFY... yes
checking for LIBCANBERRA... yes
checking for ISOCODES... yes
configure: iso-codes prefix: /usr
checking whether C compiler accepts -pipe... yes
checking whether C compiler accepts -funsigned-char... yes
checking whether C compiler accepts -fPIE... yes
checking whether C compiler accepts -fPIC... yes
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Wextra... yes
checking whether C compiler accepts -Wstrict-prototypes... yes
checking whether C compiler accepts -Wno-unused-parameter... yes
checking whether C compiler accepts -Wno-sign-compare... yes
checking whether C compiler accepts -Wno-pointer-sign... yes
checking whether C compiler accepts -Wno-missing-field-initializers... yes
checking whether C compiler accepts -Wno-unused-result... yes
checking whether C compiler accepts -Werror=format-security... yes
checking whether C compiler accepts -Werror=init-self... yes
checking whether C compiler accepts -Werror=declaration-after-statement... yes
checking whether C compiler accepts -Werror=missing-include-dirs... yes
checking whether C compiler accepts -Werror=date-time... yes
checking whether C compiler accepts -Werror=implicit-function-declaration... yes
checking whether C compiler accepts -Werror=pointer-arith... yes
checking whether C compiler accepts -fstack-protector-strong... yes
checking whether the linker accepts -pie... yes
checking whether the linker accepts -Wl,-z,relro... yes
checking whether the linker accepts -Wl,-z,now... yes
checking for modern sigaction... yes
checking for memrchr... yes
checking for gethostbyname... yes
checking for gethostname... yes
checking for strings.h... (cached) yes
checking for socklen_t... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating data/Makefile
config.status: creating data/icons/Makefile
config.status: creating data/misc/Makefile
config.status: creating data/man/Makefile
config.status: creating data/man/hexchat.1
config.status: creating data/pkgconfig/Makefile
config.status: creating data/pkgconfig/hexchat-plugin.pc
config.status: creating src/Makefile
config.status: creating src/common/Makefile
config.status: creating src/common/dbus/Makefile
config.status: creating src/fe-text/Makefile
config.status: creating src/fe-gtk/Makefile
config.status: creating src/htm/Makefile
config.status: creating src/htm/thememan
config.status: creating osx/Info.plist
config.status: creating plugins/Makefile
config.status: creating plugins/lua/Makefile
config.status: creating plugins/python/Makefile
config.status: creating plugins/perl/Makefile
config.status: creating plugins/checksum/Makefile
config.status: creating plugins/fishlim/Makefile
config.status: creating plugins/sysinfo/Makefile
config.status: creating po/Makefile.in
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default-1 commands
config.status: executing po/stamp-it commands

HexChat 2.12.4

GTK+ interface ........ : yes
Text interface ........ : yes
Theme manager ......... : no

OpenSSL support ....... : yes
D-Bus support ......... : yes
libnotify support ..... : yes
libcanberra support ... : yes
Plugin interface ...... : yes
libproxy support ...... : yes

Lua ................... : yes (lua5.3)
Perl .................. : yes
Python ................ : python-2.7

Checksum .............. : yes
FiSHLiM ............... : yes
SysInfo ............... : no

Debug mode ............ : yes

The binary will be installed in /usr/local/bin

configure complete, now type 'make' and pray.

@hexchat>make
make  all-recursive
make[1]: Entering directory '/home/kfogel/src/hexchat'
Making all in po
make[2]: Entering directory '/home/kfogel/src/hexchat/po'
  MSGFMT af.gmo
  MSGFMT am.gmo
  MSGFMT ast.gmo
  MSGFMT az.gmo
  MSGFMT be.gmo
  MSGFMT bg.gmo
  MSGFMT ca.gmo
  MSGFMT cs.gmo
  MSGFMT da.gmo
  MSGFMT de.gmo
  MSGFMT el.gmo
  MSGFMT en_GB.gmo
  MSGFMT es.gmo
  MSGFMT et.gmo
  MSGFMT eu.gmo
  MSGFMT fi.gmo
  MSGFMT fr.gmo
  MSGFMT gl.gmo
  MSGFMT gu.gmo
  MSGFMT hi.gmo
  MSGFMT hu.gmo
  MSGFMT id.gmo
  MSGFMT it.gmo
  MSGFMT ja_JP.gmo
  MSGFMT kn.gmo
  MSGFMT ko.gmo
  MSGFMT lt.gmo
  MSGFMT lv.gmo
  MSGFMT mk.gmo
  MSGFMT ml.gmo
  MSGFMT ms.gmo
  MSGFMT nb.gmo
  MSGFMT nl.gmo
  MSGFMT no.gmo
  MSGFMT pa.gmo
  MSGFMT pl.gmo
  MSGFMT pt.gmo
  MSGFMT pt_BR.gmo
  MSGFMT ru.gmo
  MSGFMT rw.gmo
  MSGFMT sk.gmo
  MSGFMT sl.gmo
  MSGFMT sq.gmo
  MSGFMT sr.gmo
  MSGFMT sr@latin.gmo
  MSGFMT sv.gmo
  MSGFMT th.gmo
  MSGFMT tr.gmo
  MSGFMT uk.gmo
  MSGFMT vi.gmo
  MSGFMT wa.gmo
  MSGFMT zh_CN.gmo
  MSGFMT zh_TW.gmo
make[2]: Leaving directory '/home/kfogel/src/hexchat/po'
Making all in src
make[2]: Entering directory '/home/kfogel/src/hexchat/src'
Making all in common
make[3]: Entering directory '/home/kfogel/src/hexchat/src/common'
  CC       make-te.o
  CCLD     make-te
  GEN      textevents.h
  GEN      marshal.c
  GEN      marshal.h
make  all-recursive
make[4]: Entering directory '/home/kfogel/src/hexchat/src/common'
Making all in dbus
make[5]: Entering directory '/home/kfogel/src/hexchat/src/common/dbus'
  GEN      remote-object-glue.h
make  all-am
make[6]: Entering directory '/home/kfogel/src/hexchat/src/common/dbus'
  CC       dbus-plugin.o
  CC       dbus-client.o
  AR       libhexchatdbus.a
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       example.o
  CCLD     example
make[6]: Leaving directory '/home/kfogel/src/hexchat/src/common/dbus'
make[5]: Leaving directory '/home/kfogel/src/hexchat/src/common/dbus'
Making all in .
make[5]: Entering directory '/home/kfogel/src/hexchat/src/common'
  CC       libhexchatcommon_a-cfgfiles.o
  CC       libhexchatcommon_a-chanopt.o
  CC       libhexchatcommon_a-ctcp.o
  CC       libhexchatcommon_a-dcc.o
  CC       libhexchatcommon_a-hexchat.o
  CC       libhexchatcommon_a-history.o
  CC       libhexchatcommon_a-ignore.o
  CC       libhexchatcommon_a-inbound.o
  CC       libhexchatcommon_a-marshal.o
  CC       libhexchatcommon_a-modes.o
  CC       libhexchatcommon_a-network.o
  CC       libhexchatcommon_a-notify.o
  CC       libhexchatcommon_a-outbound.o
  CC       libhexchatcommon_a-plugin.o
  CC       libhexchatcommon_a-plugin-identd.o
  CC       libhexchatcommon_a-plugin-timer.o
  CC       libhexchatcommon_a-proto-irc.o
  CC       libhexchatcommon_a-server.o
  CC       libhexchatcommon_a-servlist.o
  CC       libhexchatcommon_a-ssl.o
ssl.c: In function ‘_SSL_get_cert_info’:
ssl.c:180:35: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’
  sign_alg = OBJ_obj2nid (peer_cert->sig_alg->algorithm);
                                   ^~
ssl.c: In function ‘_SSL_socket’:
ssl.c:310:14: error: dereferencing pointer to incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
  method = ctx->method;
              ^~
ssl.c: In function ‘_SSL_close’:
ssl.c:352:2: warning: ‘ERR_remove_state’ is deprecated [-Wdeprecated-declarations]
  ERR_remove_state (0);    /* free state buffer */
  ^~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from ssl.c:26:
/usr/include/openssl/err.h:247:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
ssl.c: In function ‘_SSL_check_subject_altname’:
ssl.c:447:5: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
     data = ASN1_STRING_data (altname->d.dNSName);
     ^~~~
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from ssl.c:26:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
ssl.c:473:4: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
    data = ASN1_STRING_data (altname->d.iPAddress);
    ^~~~
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from ssl.c:26:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
Makefile:943: recipe for target 'libhexchatcommon_a-ssl.o' failed
make[5]: *** [libhexchatcommon_a-ssl.o] Error 1
make[5]: Leaving directory '/home/kfogel/src/hexchat/src/common'
Makefile:1060: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/home/kfogel/src/hexchat/src/common'
Makefile:563: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/kfogel/src/hexchat/src/common'
Makefile:447: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/kfogel/src/hexchat/src'
Makefile:501: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/kfogel/src/hexchat'
Makefile:431: recipe for target 'all' failed
make: *** [all] Error 2
$
```

**Comment by TingPing** [comment]
@kfogel Your problem is these all failed:

```
checking for SSL_CTX_get_ssl_method... no
checking for X509_get_signature_nid... no
checking for DH_set0_pqg... no
checking for DH_get0_key... no
checking for DH_set0_key... no
```

So figure out why, without those functions there is nothing we can do anyway.

**Comment by kfogel** [comment]
Thanks, @TingPing.  I'll look into it; probably some Debian package I need to install.

**Comment by TingPing** [comment]
@kfogel Well a few months ago you probably had OpenSSL 1.0 but on top of that we recently added these function checks for 1.1.

**Comment by kfogel** [comment]
Ah, I see.  Okay -- almost certainly some Debian GNU/Linux dev library configuration or inclusion issue then.  I'll look into it.  If anything looks like it has broader import for hexchat I'll report back here, but doubt that will be the case.
