### ISSUE TITLE
Universal Plug n Play doesn't work, Windows 8.1 64bit

### ISSUE THREAD

**Issue by dwhagar** [hexchat/hexchat#1291]
Universal plug'n'play for port forwarding to DCC connections doesn't work at all under Windows 8.1 64bit.  Works on the Mac and Linux versions just fine, however.

**Comment by TingPing** [comment]
HexChat itself does not implement upnp at all

**Comment by dwhagar** [comment]
That explains that.  Must be something about the libraries used as part of the OS for Linux and Mac.  I know that this, http://miniupnp.free.fr/xchat-upnp.html once worked with XChat 2.6.6 I wondered if it could be incorporated into HexChat?  I am a coder but my skills are not up to it.  I'm sorry for that.

Again, thank you for keeping up an open source IRC client.

**Comment by TingPing** [comment]
If HexChat were to implement upnp it would likely be using [GUPnP](https://developer.gnome.org/gupnp/unstable/) but this adds dependencies for a feature few care about. The maintainers of the Windows builds certainly don't want to build more things.

**Comment by dwhagar** [comment]
Thank you for the update. What is required to open the windows build source
code?

**Comment by somercet** [comment]
Sorry to kick up an old issue, but:

I got the miniupnp patch to work with Hexchat, and I would like to offer it on Arch's AUR (unofficial repository). But if you think a GUPnP patch would be wiser, or more acceptable, I would be interested your thoughts.

Thanks for your time!

**Comment by feiercrack** [comment]
> Sorry to kick up an old issue, but:
> 
> I got the miniupnp patch to work with Hexchat, and I would like to offer it on Arch's AUR (unofficial repository). But if you think a GUPnP patch would be wiser, or more acceptable, I would be interested your thoughts.
> 
> Thanks for your time!

wow, may i also have this patch?

**Comment by somercet** [comment]
> wow, may i also have this patch?

Hang on, I don't have it on this machine. Lemme remake the patch.

**Comment by somercet** [comment]
> wow, may i also have this patch?

https://github.com/somercet/hexchat/tree/miniupnpc

If you get this running, let me know, I'd love to test with another Hexchat client.

**Comment by TingPing** [comment]
The reason I recommended GUPnP is because it is properly asynchronous. This patch locks up the application every time it does IO, potentially causing bugs/crashes, but mostly just makes it an inconsistent and sometimes poor experience.

**Comment by somercet** [comment]
Yes, that is better, and I'm working on it now. Fortunately, in the mean time, I don't do DCC much.

**Comment by BigBroza** [comment]
> Yes, that is better, and I'm working on it now. Fortunately, in the mean time, I don't do DCC much.

Hello @somercet 
Could you please share binaries of your upnp/gupnp fork please? I can't build.
Appreciated, thank you.

And I hope hexchat adds this because this feature is essential to download from passive servers.
