### ISSUE TITLE
HexChat 2.10.2 fails to build with OpenSSL 0.9 branch

### ISSUE THREAD

**Issue by vaygr** [hexchat/hexchat#1221]
While upgrading from 2.10.1 here what do we get:

```
ssl.c: In function '_SSL_context_init':
ssl.c:94:2: error: 'SSL_OP_NO_COMPRESSION' undeclared (first use in this function)
ssl.c:94:2: note: each undeclared identifier is reported only once for each function it appears in
```

Maybe something like this patch is needed:

``` diff
--- ssl.c.orig  2014-11-25 20:42:31.000000000 +0300
+++ ssl.c   2014-11-26 12:45:44.000000000 +0300
@@ -92,11 +92,17 @@
    SSL_CTX_set_session_cache_mode (ctx, SSL_SESS_CACHE_BOTH);
    SSL_CTX_set_timeout (ctx, 300);
    SSL_CTX_set_options (ctx, SSL_OP_NO_SSLv2|SSL_OP_NO_SSLv3
+#ifdef SSL_OP_NO_COMPRESSION
                              |SSL_OP_NO_COMPRESSION
+#endif
                              |SSL_OP_SINGLE_DH_USE|SSL_OP_SINGLE_ECDH_USE
                              |SSL_OP_NO_TICKET
                              |SSL_OP_CIPHER_SERVER_PREFERENCE);

+#if OPENSSL_VERSION_NUMBER >= 0x00908000L /* workaround for OpenSSL 0.9.8 */
+   sk_SSL_COMP_zero(SSL_COMP_get_compression_methods());
+#endif
+
    /* used in SSL_connect(), SSL_accept() */
    SSL_CTX_set_info_callback (ctx, info_cb_func);

```
