### ISSUE TITLE
Fails to build on OSX < 10.10

### ISSUE THREAD

**Issue by aint** [hexchat/hexchat#1657]
Hi, there. Where I can donwload the latest version for OS X? It looks like only 2.10.2 is available for Mac. So I tried to build 2.12.0 from sources (via homebrew), but got following errors:
```make
Last 15 lines from /Users/aint/Library/Logs/Homebrew/hexchat/02.make:
Making install in sysinfo
  CC       format.lo
  CC       sysinfo.lo
  OBJC     osx/backend.lo
  CC       shared/df.lo
osx/backend.m:82:2: error: use of undeclared identifier 'NSOperatingSystemVersion'
        NSOperatingSystemVersion version = [info operatingSystemVersion];
        ^
osx/backend.m:84:46: error: use of undeclared identifier 'version'
        return g_strdup_printf ("OS X %ld.%ld.%ld", version.majorVersion, version.minorVersion, version.patchVersion);
                                                    ^
2 errors generated.
make[2]: *** [osx/backend.lo] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

**Comment by TingPing** [comment]
Well you opened one issue for two problems...

> but got following errors:

Looks like this API was added in 10.10, you can build with `./configure --disable-sysinfo` for now.

>  Where I can donwload the latest version for OS X?

I no longer have an OSX install and have no real interest in provide a release since it was so bad anyway. distributors like homebrew and macports will have to step up.

**Comment by aint** [comment]
Ok, thanks. Sorry for trouble.

**Comment by TingPing** [comment]
Fixed by 49758cafba9fd7e0663b550debfd51fb21260650

**Comment by Ionic** [comment]
... with a fixup in 65abf5c5324536b14985689bb97af61bf439d651. Sorry.
