### ISSUE TITLE
pywintypes throws errors only in HexChat not in Python 2.7 or PythonWin

### ISSUE THREAD

**Issue by XcomReborn** [hexchat/hexchat#480]
I have written two python scripts for  HexChat. The first was a winamp controller that sent commands to a winamp.py script to control winamp based on user text commands read from IRC. 

The python script would work on first load, but after unloading and reloading it would throw an error.

```
File "C:\Python27\Lib\winamp2.py", line 27, in <module>
import win32api, win32con, win32gui, win32process, pywintypes
File "C:\Python27\lib\site-packages\win32\lib\pywintypes.py", line 124, in <module>
__import_pywin32_system_module__("pywintypes", globals())
File "C:\Python27\lib\site-packages\win32\lib\pywintypes.py", line 114, in __import_pywin32_system_module__
assert sys.modules[modname] is old_mod
TypeError: 'NoneType' object has no attribute '__getitem__'
```

This was fixed by removing the import pywintypes from the winamp2.py file and replacing the use of it from 

```
except pywintypes.error, e:
```

to

```
except Exception, e
```

Secondly a similar error has occurred with pywintype that I haven' fixed yet.

I am trying to use the import pyttsx library to do text to speech.

Simply:

```
import pyttsx

engine = pyttsx.init()
engine.say('Greetings!')
engine.runAndWait()
```

This works in python 2.7 on in Idle and pythonwin but throws this error in HexChat.

```
 Traceback (most recent call last):
   File "C:\Users\aaa\AppData\Roaming\HexChat\xxxxx.py", line 10, in <module>
     engine = pyttsx.init()
   File "C:\Python27\lib\site-packages\pyttsx\__init__.py", line 39, in init
     eng = Engine(driverName, debug)
   File "C:\Python27\lib\site-packages\pyttsx\engine.py", line 45, in __init__
     self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
   File "C:\Python27\lib\site-packages\pyttsx\driver.py", line 64, in __init__
     self._module = __import__(name, globals(), locals(), [driverName])
   File "C:\Python27\lib\site-packages\pyttsx\drivers\sapi5.py", line 19, in <module>
     import win32com.client
   File "C:\Python27\lib\site-packages\win32com\__init__.py", line 6, in <module>
     import pythoncom
   File "C:\Python27\lib\site-packages\pythoncom.py", line 2, in <module>
     import pywintypes
   File "C:\Python27\lib\site-packages\win32\lib\pywintypes.py", line 124, in <module>
     __import_pywin32_system_module__("pywintypes", globals())
   File "C:\Python27\lib\site-packages\win32\lib\pywintypes.py", line 114, in __import_pywin32_system_module__
     assert sys.modules[modname] is old_mod
 TypeError: 'NoneType' object has no attribute '__getitem__'
```

I asked on Stackoverflow and they seem to this is problem is with the python interpreter in HexChat.
